name: Build and Submit to IOS TestFlight

on:
  push:
    branches:
      - staging

jobs:
  build_ios:
    name: Build iOS App
    type: build
    params:
      platform: ios
      profile: staging

  testflight:
    name: Distribute to TestFlight
    type: testflight
    needs: [build_ios]
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      internal_groups: ['Internal']
      external_groups: []
      changelog: "${{ github.commit_message || 'Bug fixes' }}"
