name: Deploy to IOS - [staging]

on:
  push:
    branches:
      - staging

jobs:
  build_ios:
    name: Build iOS App
    type: build
    params:
      platform: ios
      profile: staging

  publish_testflight:
    needs: [build_ios]
    name: Distribute to TestFlight
    type: testflight
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      internal_groups: ['Internal']
      external_groups: []
      changelog: "${{ github.commit_message || 'Bug fixes' }}"

  custom_comment:
    name: Post Custom Comment
    needs: [build_ios]
    type: github-comment
    params:
      payload: |
        ## 🚀 Build Status Update

        ### iOS Build Completed
        - **Build ID**: `${{ needs.build_ios.outputs.build_id }}`
        - **Version**: ${{ needs.build_ios.outputs.app_version }}
        - **Build Number**: ${{ needs.build_ios.outputs.app_build_version }}

        ### Next Steps
        1. Download the build from [EAS Dashboard](https://expo.dev/accounts/[account]/projects/[project]/builds/${{ needs.build_ios.outputs.build_id }})
        2. Test on physical device
        3. Approve for TestFlight distribution

        ---
        *This comment was automatically generated by EAS Workflows*
