name: Auto Create PR to DEV
on:
  push:
    branches:
      - feat/*
      - feature/*
      - update/*
      - bugfix/*
      - hotfix/*
      - fix/*
      - chore/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const { repo, owner } = context.repo;

             const branchName = context.ref.replace('refs/heads/', '');

            const pulls = await github.rest.pulls.list({
              owner: owner,
              repo: repo,
              head: context.ref,
              base: 'develop',
              state: 'open',
            });

            const existingPR = pulls.data.find(pr => pr.head.ref === branchName);

            if (!existingPR) {
              console.log(`No existing PR found for branch ${branchName}. Creating a new one.`);
              await github.rest.pulls.create({
                title: `CI: Merge '${branchName}' into develop`,
                owner,
                repo,
                head: branchName,
                base: 'develop',
                body: [
                  'This PR is auto-generated by',
                  '[CI BOT](https://github.com/actions/github-script)',
                ].join('\n'),
              });
            } else {
               await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: existingPR.number,
                body: `🔄 Branch \`${branchName}\` was updated. Triggered by job \`${context.job}\`.`,
              });
            }
